# Generated by Django 4.0.1 on 2022-01-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('CANCELED', 'CANCELED'), ('ACCEPTED', 'ACCEPTED'), ('FINISHED', 'FINISHED')], default='CREATED', max_length=8)),
                ('start_point_lat', models.CharField(max_length=63)),
                ('start_point_long', models.CharField(max_length=63)),
                ('end_point_lat', models.CharField(max_length=63)),
                ('end_point_long', models.CharField(max_length=63)),
                ('amount', models.PositiveIntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='drivers.driver')),
            ],
            options={
                'ordering': ('modified_date',),
            },
        ),
    ]
